from game.models import *

User.objects.all().delete()
Challenges.objects.all().delete()

Challenges.objects.create(name="Ask someone to swap drinks with you", rating="Easy")
Challenges.objects.create(name="Compliment someone in a silly or exaggerated way", rating="Easy")
Challenges.objects.create(name="Make someone laugh in under 10 seconds", rating="Easy")
Challenges.objects.create(name="Do a dramatic entrance like you're on a catwalk", rating="Easy")
Challenges.objects.create(name="Ask someone a funny or random question about themselves", rating="Easy")
Challenges.objects.create(name="Do a secret handshake with someone", rating="Easy")
Challenges.objects.create(name="Tell a funny or embarrassing childhood story", rating="Easy")
Challenges.objects.create(name="Give someone a nickname on the spot", rating="Easy")
Challenges.objects.create(name="Take a silly selfie with someone else", rating="Easy")
Challenges.objects.create(name="Say something nice to someone in a funny accent", rating="Easy")
Challenges.objects.create(name="Ask someone to make a funny face for a photo", rating="Easy")
Challenges.objects.create(name="Ask someone to show you their best dance move", rating="Easy")
Challenges.objects.create(name="Whisper something ridiculous to someone and make them repeat it out loud", rating="Easy")
Challenges.objects.create(name="Do a dramatic slow clap for someone", rating="Easy")
Challenges.objects.create(name="Ask someone to act like a statue for 10 seconds", rating="Easy")
Challenges.objects.create(name="Make a joke and try to get at least one person to groan", rating="Easy")
Challenges.objects.create(name="Ask someone to name the silliest thing they’ve done today", rating="Easy")
Challenges.objects.create(name="Do a funny handshake with two different people", rating="Easy")
Challenges.objects.create(name="Ask someone to tell a fake celebrity gossip story", rating="Easy")
Challenges.objects.create(name="Pretend to be a news reporter and interview someone", rating="Easy")
Challenges.objects.create(name="Ask someone to teach you a weird skill they have", rating="Easy")
Challenges.objects.create(name="Give someone a dramatic award for something silly", rating="Easy")
Challenges.objects.create(name="Ask someone to say a tongue twister", rating="Easy")
Challenges.objects.create(name="Do an exaggerated bow or curtsy to someone", rating="Easy")
Challenges.objects.create(name="Ask someone to make a ridiculous face contest with you", rating="Easy")
Challenges.objects.create(name="Try to get someone to laugh at a terrible pun", rating="Easy")
Challenges.objects.create(name="Ask someone to mimic an animal sound", rating="Easy")
Challenges.objects.create(name="Make someone tell you a funny story about someone else at the party", rating="Easy")
Challenges.objects.create(name="Pretend to be a waiter and take someone's order dramatically", rating="Easy")
Challenges.objects.create(name="Ask someone to give you a weird compliment", rating="Easy")
Challenges.objects.create(name="Act like a superhero and convince someone to join your team", rating="Easy")
Challenges.objects.create(name="Ask someone to tell a short story with a ridiculous ending", rating="Easy")
Challenges.objects.create(name="Do a dramatic reenactment of a minor event from the day", rating="Easy")
Challenges.objects.create(name="Ask someone to teach you a dance move you’ve never done", rating="Easy")
Challenges.objects.create(name="Ask someone to speak in a funny accent for a moment", rating="Easy")
Challenges.objects.create(name="Make someone do a quick dramatic pose", rating="Easy")
Challenges.objects.create(name="Ask someone to tell their most embarrassing nickname", rating="Easy")
Challenges.objects.create(name="Pretend to be a celebrity and ask someone to be your fan", rating="Easy")
Challenges.objects.create(name="Do a silly walk across the room with someone", rating="Easy")
Challenges.objects.create(name="Ask someone to rate your imaginary pet", rating="Easy")
Challenges.objects.create(name="Ask someone to demonstrate their best model walk", rating="Easy")
Challenges.objects.create(name="Convince someone to sing the alphabet backwards", rating="Easy")
Challenges.objects.create(name="Ask someone to do a dramatic gasp for no reason", rating="Easy")
Challenges.objects.create(name="Pretend to be a mime and get someone to copy you", rating="Easy")
Challenges.objects.create(name="Ask someone to describe a food as dramatically as possible", rating="Easy")
Challenges.objects.create(name="Ask someone to invent a handshake with you", rating="Easy")
Challenges.objects.create(name="Make someone tell you a joke and rate it 1-10", rating="Easy")
Challenges.objects.create(name="Ask someone to compliment you like a game show host", rating="Easy")
Challenges.objects.create(name="Ask someone to demonstrate the silliest pose they know", rating="Easy")
Challenges.objects.create(name="Do a dramatic slow-motion walk with someone", rating="Easy")
Challenges.objects.create(name="Ask someone to make a funny sound and repeat it", rating="Easy")

Challenges.objects.create(name="Convince someone to do a dance move with you", rating="Medium")
Challenges.objects.create(name="Make someone tell an embarrassing secret", rating="Medium")
Challenges.objects.create(name="Ask someone to serenade you with a short song", rating="Medium")
Challenges.objects.create(name="Get someone to swap an article of clothing with you", rating="Medium")
Challenges.objects.create(name="Convince someone to talk in a silly voice", rating="Medium")
Challenges.objects.create(name="Make someone compliment everyone around in a funny way", rating="Medium")
Challenges.objects.create(name="Ask someone to take a dramatic selfie with you", rating="Medium")
Challenges.objects.create(name="Convince someone to do a funny impression of a celebrity", rating="Medium")
Challenges.objects.create(name="Ask someone to give you their best pickup line", rating="Medium")
Challenges.objects.create(name="Get someone to tell a made-up, ridiculous story about themselves", rating="Medium")
Challenges.objects.create(name="Convince someone to pretend to be a waiter and take an order dramatically", rating="Medium")
Challenges.objects.create(name="Ask someone to perform a dramatic monologue about a mundane object", rating="Medium")
Challenges.objects.create(name="Convince someone to do a silly runway walk", rating="Medium")
Challenges.objects.create(name="Make someone act like a superhero and save the party", rating="Medium")
Challenges.objects.create(name="Get someone to read a text message dramatically", rating="Medium")
Challenges.objects.create(name="Ask someone to describe someone else at the party in the style of a movie trailer", rating="Medium")
Challenges.objects.create(name="Convince someone to demonstrate their best dance move", rating="Medium")
Challenges.objects.create(name="Get someone to create a new handshake with you", rating="Medium")
Challenges.objects.create(name="Ask someone to tell a joke in the style of a Shakespearean character", rating="Medium")
Challenges.objects.create(name="Make someone sing a silly song loudly", rating="Medium")
Challenges.objects.create(name="Convince someone to speak in a funny accent", rating="Medium")
Challenges.objects.create(name="Ask someone to invent a new drink and explain why it's the best", rating="Medium")
Challenges.objects.create(name="Get someone to pretend to be your personal bodyguard", rating="Medium")
Challenges.objects.create(name="Ask someone to give you a dramatic weather report", rating="Medium")
Challenges.objects.create(name="Convince someone to act like a cat or dog for a few seconds", rating="Medium")
Challenges.objects.create(name="Ask someone to describe their outfit like a fashion critic", rating="Medium")
Challenges.objects.create(name="Get someone to do a dramatic pose like they're on a magazine cover", rating="Medium")
Challenges.objects.create(name="Convince someone to tell a story with every sentence starting with 'And then...'", rating="Medium")
Challenges.objects.create(name="Ask someone to make a toast in the style of a pirate", rating="Medium")
Challenges.objects.create(name="Get someone to pretend to be a statue and hold a pose while you take a photo", rating="Medium")
Challenges.objects.create(name="Convince someone to give an impromptu motivational speech", rating="Medium")
Challenges.objects.create(name="Ask someone to narrate someone else's actions dramatically", rating="Medium")
Challenges.objects.create(name="Get someone to tell a story using only sound effects", rating="Medium")
Challenges.objects.create(name="Convince someone to act like a famous movie character", rating="Medium")
Challenges.objects.create(name="Ask someone to make up a ridiculous slogan for the party", rating="Medium")
Challenges.objects.create(name="Get someone to do a mock fashion show with you", rating="Medium")
Challenges.objects.create(name="Convince someone to perform a dramatic reaction to an ordinary object", rating="Medium")
Challenges.objects.create(name="Ask someone to tell a funny story about the host", rating="Medium")
Challenges.objects.create(name="Get someone to act out an argument between two imaginary people", rating="Medium")
Challenges.objects.create(name="Convince someone to do a silly walk across the room", rating="Medium")
Challenges.objects.create(name="Ask someone to give you a dramatic award for something minor", rating="Medium")
Challenges.objects.create(name="Get someone to pretend to be a famous singer for 30 seconds", rating="Medium")
Challenges.objects.create(name="Convince someone to do a funny dance with an invisible partner", rating="Medium")
Challenges.objects.create(name="Ask someone to recite a dramatic poem about food", rating="Medium")
Challenges.objects.create(name="Get someone to tell a story in the style of a news broadcast", rating="Medium")
Challenges.objects.create(name="Convince someone to act like a game show host", rating="Medium")
Challenges.objects.create(name="Ask someone to describe their life as if it were a soap opera", rating="Medium")
Challenges.objects.create(name="Get someone to make a fake commercial for a random object", rating="Medium")
Challenges.objects.create(name="Convince someone to do a dramatic slow-motion walk", rating="Medium")
Challenges.objects.create(name="Ask someone to act like they're in a horror movie for a few seconds", rating="Medium")
Challenges.objects.create(name="Get someone to pretend to win an award and give an acceptance speech", rating="Medium")

Challenges.objects.create(name="Convince someone to do a dare chosen by the group", rating="Hard")
Challenges.objects.create(name="Get someone to call a random person and sing 'Happy Birthday'", rating="Hard")
Challenges.objects.create(name="Ask someone to swap an item of clothing with you", rating="Hard")
Challenges.objects.create(name="Make someone do a dramatic dance solo in front of everyone", rating="Hard")
Challenges.objects.create(name="Convince someone to do a funny dare involving a drink", rating="Hard")
Challenges.objects.create(name="Get someone to let you style their hair however you want", rating="Hard")
Challenges.objects.create(name="Ask someone to loudly proclaim a silly statement", rating="Hard")
Challenges.objects.create(name="Convince someone to give you a funny nickname", rating="Hard")
Challenges.objects.create(name="Get someone to do a mock proposal or dramatic confession", rating="Hard")
Challenges.objects.create(name="Ask someone to do a silly runway walk across the room", rating="Hard")
Challenges.objects.create(name="Convince someone to do a dramatic karaoke performance", rating="Hard")
Challenges.objects.create(name="Get someone to pretend to be your personal assistant for a few minutes", rating="Hard")
Challenges.objects.create(name="Ask someone to act like a celebrity and give an autograph", rating="Hard")
Challenges.objects.create(name="Convince someone to wear a silly hat or accessory you pick", rating="Hard")
Challenges.objects.create(name="Get someone to do a funny impression of someone else at the party", rating="Hard")
Challenges.objects.create(name="Ask someone to act like a game show contestant and answer ridiculous questions", rating="Hard")
Challenges.objects.create(name="Convince someone to tell an embarrassing story about themselves", rating="Hard")
Challenges.objects.create(name="Get someone to perform a dramatic reading of a text or social media post", rating="Hard")
Challenges.objects.create(name="Ask someone to sing a song chosen by the group loudly", rating="Hard")
Challenges.objects.create(name="Convince someone to make a speech about a ridiculous topic", rating="Hard")
Challenges.objects.create(name="Get someone to pretend to be a superhero saving the party", rating="Hard")
Challenges.objects.create(name="Ask someone to act like a famous movie scene and reenact it", rating="Hard")
Challenges.objects.create(name="Convince someone to perform a silly dance with you in the middle of the room", rating="Hard")
Challenges.objects.create(name="Get someone to pretend to be an animal and interact with the group", rating="Hard")
Challenges.objects.create(name="Ask someone to give an impromptu weather report dramatically", rating="Hard")
Challenges.objects.create(name="Convince someone to narrate someone else’s actions like a sports commentator", rating="Hard")
Challenges.objects.create(name="Get someone to do a mock awards ceremony for the party", rating="Hard")
Challenges.objects.create(name="Ask someone to pretend to be a news anchor and report something ridiculous", rating="Hard")
Challenges.objects.create(name="Convince someone to act like they just won a million dollars", rating="Hard")
Challenges.objects.create(name="Get someone to give an over-the-top dramatic apology to the group", rating="Hard")
Challenges.objects.create(name="Ask someone to act like they are in slow motion while moving around", rating="Hard")
Challenges.objects.create(name="Convince someone to make up a new handshake involving the whole group", rating="Hard")
Challenges.objects.create(name="Get someone to perform a silly skit with a random person", rating="Hard")
Challenges.objects.create(name="Ask someone to pretend to be a famous singer and perform a hit song", rating="Hard")
Challenges.objects.create(name="Convince someone to wear an item of clothing in a ridiculous way", rating="Hard")
Challenges.objects.create(name="Get someone to read a message in the most dramatic way possible", rating="Hard")
Challenges.objects.create(name="Ask someone to do a dramatic slow-motion reaction to an ordinary object", rating="Hard")
Challenges.objects.create(name="Convince someone to tell a fake story with outrageous details", rating="Hard")
Challenges.objects.create(name="Get someone to imitate a famous TV character", rating="Hard")
Challenges.objects.create(name="Ask someone to pretend to be a fashion model and do a catwalk", rating="Hard")
Challenges.objects.create(name="Convince someone to perform a mock press conference about something silly", rating="Hard")
Challenges.objects.create(name="Get someone to act like a villain in a movie scene", rating="Hard")
Challenges.objects.create(name="Ask someone to pretend to be a robot and interact with people", rating="Hard")
Challenges.objects.create(name="Convince someone to give a dramatic toast about something ridiculous", rating="Hard")
Challenges.objects.create(name="Get someone to perform a funny ritual or chant for the party", rating="Hard")
Challenges.objects.create(name="Ask someone to make up a ridiculous commercial on the spot", rating="Hard")
Challenges.objects.create(name="Convince someone to act like a celebrity walking through paparazzi", rating="Hard")
Challenges.objects.create(name="Get someone to pretend to be a judge and give a ridiculous verdict", rating="Hard")
Challenges.objects.create(name="Ask someone to perform a silly sports commentary", rating="Hard")
Challenges.objects.create(name="Convince someone to do a mock interview with another guest", rating="Hard")
Challenges.objects.create(name="Get someone to give a dramatic weather forecast for an imaginary event", rating="Hard")
Challenges.objects.create(name="Ask someone to pretend to be a movie trailer narrator and describe the party", rating="Hard")
